### ISSUE TITLE
Simplex Form for (some) U.S. users fails

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/telos.net#1]
**Describe the bug**
The Simplex form to purchase more Telos does not work for all U.S. residents but allows them to input all of their information and displays a misleading USD conversion input implying it is possible. This can be frustrating for the end user. Seems to only succeed for certain states. See additional notes. 

**To Reproduce**
1. Go to telos.net
2. Scroll down to simplex form ('Buy TLOS with FIAT instantly.')
3. Using VPN based in eligible U.S. state or otherwise from eligible U.S. territory IP fill out form and submit
4. *See error and inability to click 'Done' to dismiss error

*See additional notes

**Expected behavior**
Should be either hidden or disabled (with notification) for unsupported countries.

**Screenshots**
![image](https://github.com/telosnetwork/telos.net/assets/6848910/b4ddcaaa-8dda-4e80-9dd9-b18cfd0b2141)
![image](https://user-images.githubusercontent.com/6848910/231839972-ecce5b53-962e-47f8-9dea-6db079c630d8.png)

**Additional Notes**
- seems to only affect certain U.S. states (?), according to their site, only New York and Hawaii should be affected: https://support.simplex.com/hc/en-gb/articles/360014137459-What-are-your-supported-locations-countries-states-and-territories-
- error above is from Florida

**Comment by yaroslav-borodii** [comment]
Not related to Webflow, this issue is on the Simplex side as it's an iframe.
