### ISSUE TITLE
'Submit a Support Request' link forwards to expired/invalid discord invite link

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/telos.net#3]
**Describe the bug**
on https://help.telos.net/ the 'Submit a Support Request' (top right) forwards to an expired discord invite link: https://discord.com/invite/Crs6JKtN

![image](https://github.com/telosnetwork/telos.net/assets/6848910/9d8307fc-ab8e-478a-8fe4-5cc098b218e0)

**Additional Notes**
update link to use the general: https://discord.gg/telosnetwork

**Comment by jbuice** [comment]
The link should be updated to https://discord.gg/telosnetwork on help.telos.net.

**Comment by donnyquixotic** [comment]
resolved

**Comment by donnyquixotic** [comment]
@jbuice getting the same invite invalid message again w/ https://discord.gg/telosnetwork ?

**Comment by donnyquixotic** [comment]
updated to permalink: discord.gg/telos
