### ISSUE TITLE
Wrong url for swapsicle

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/telos.net#7]
**Describe the bug**
The link for Swapsicle is incorrect. It links to https://www.swapsicle.io/ru (404). It should be https://www.swapsicle.io or https://app.swapsicle.io/swap.

**To Reproduce**
1. Go to https://www.telos.net/ecosystem-apps-filter/defi?tab=evm
2. Click on 'swapsicle' 
3. See 404

**Expected behavior**
should redirect to main site

**Comment by yaroslav-borodii** [comment]
Hey @donnyquixotic,
Thanks for the bug report!

It has been fixed, please check again.
